title: Wonha Shin # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Master Student @ Univ. of Rochester 
  <br><br>
  Driven by an unwavering passion for data-driven insights and a commitment to improving lives through data science. Particularly fascinated by the potential of Natural Language Processing (NLP) to decode information and enhance human experiences. Eager to contribute to the forefront of NLP applications and use data analytics to bring about positive change in diverse areas.
  <br><br>
  <a href="https://www.linkedin.com/in/wshin7/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
